ExpressVoitures/ExpressVoitures/Controllers/ReparationsController.cs
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace ExpressVoitures.Controllers
{
    // Restreindre l'accès aux administrateurs
    [Authorize(Roles = "Admin")] 
    public class ReparationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ReparationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reparations
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Reparations.Include(r => r.TypeReparation).Include(r => r.Vehicule);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Reparations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reparation = await _context.Reparations
                .Include(r => r.TypeReparation)
                .Include(r => r.Vehicule)
                .FirstOrDefaultAsync(m => m.ReparationId == id);
            if (reparation == null)
            {
                return NotFound();
            }

            return View(reparation);
        }

        // GET: Reparations/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["VehiculeId"] = new SelectList(_context.Vehicules, "VehiculeId", "CodeVIN");
            ViewData["TypeReparationId"] = new SelectList(_context.TypeReparations, "TypeReparationId", "Nom");
            return View();
        }


        // POST: Reparations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Reparation reparation, string? NouveauType)
        {
            // Si l'utilisateur a écrit un nouveau type
            if (!string.IsNullOrWhiteSpace(NouveauType))
            {
                var existing = await _context.TypeReparations
                    .FirstOrDefaultAsync(t => t.Nom == NouveauType);


                if (existing == null)
                {
                    var type = new TypeReparation { Nom = NouveauType };
                    _context.TypeReparations.Add(type);
                    await _context.SaveChangesAsync();

                    reparation.TypeReparationId = type.TypeReparationId;
                }
                else
                {
                    reparation.TypeReparationId = existing.TypeReparationId;
                }
            }

            // Valider et enregistrer
            if (ModelState.IsValid)
            {
                _context.Reparations.Add(reparation);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Si erreur, recharger les listes
            ViewBag.TypeReparationId = new SelectList(_context.TypeReparations, "TypeReparationId", "Nom", reparation.TypeReparationId);
            ViewBag.VehiculeId = new SelectList(_context.Vehicules, "VehiculeId", "CodeVIN", reparation.VehiculeId);
            return View(reparation);
        }




        // GET: Reparations/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            
            if (id == null)
            {
                return NotFound();
            }
            // chercher la réparation
            var reparation = await _context.Reparations.FindAsync(id);
            if (reparation == null)
            {
                return NotFound();
            }
            ViewData["TypeReparationId"] = new SelectList(_context.TypeReparations, "TypeReparationId", "Nom", reparation.TypeReparationId);
            ViewData["VehiculeId"] = new SelectList(_context.Vehicules, "VehiculeId", "CodeVIN", reparation.VehiculeId);
            return View(reparation);
        }

        // POST: Reparations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ReparationId,VehiculeId,TypeReparationId,Cout,Date")] Reparation reparation)
        {
            
            if (id != reparation.ReparationId)
            {
                return NotFound();
            }

            // valider et enregistrer
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reparation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReparationExists(reparation.ReparationId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["TypeReparationId"] = new SelectList(_context.TypeReparations, "TypeReparationId", "Nom", reparation.TypeReparationId);
            ViewData["VehiculeId"] = new SelectList(_context.Vehicules, "VehiculeId", "CodeVIN", reparation.VehiculeId);
            return View(reparation);
        }

        // GET: Reparations/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reparation = await _context.Reparations
                .Include(r => r.TypeReparation)
                .Include(r => r.Vehicule)
                .FirstOrDefaultAsync(m => m.ReparationId == id);
            if (reparation == null)
            {
                return NotFound();
            }

            return View(reparation);
        }

        // POST: Reparations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reparation = await _context.Reparations.FindAsync(id);
            if (reparation != null)
            {
                _context.Reparations.Remove(reparation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReparationExists(int id)
        {
            return _context.Reparations.Any(e => e.ReparationId == id);
        }
    }
}

ExpressVoitures/ExpressVoitures/Controllers/VehiculesController.cs
using ExpressVoitures.Data;
using ExpressVoitures.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;


namespace ExpressVoitures.Controllers
{
    public class VehiculesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _env;

        public VehiculesController(ApplicationDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }





        // GET: Vehicules
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Vehicules.Include(v => v.Finition).Include(v => v.Marque).Include(v => v.Modele);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Vehicules/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _context.Vehicules
                .Include(v => v.Finition)
                .Include(v => v.Marque)
                .Include(v => v.Modele)
                .FirstOrDefaultAsync(m => m.VehiculeId == id);
            if (vehicule == null)
            {
                return NotFound();
            }

            return View(vehicule);
        }

        // GET: Vehicules/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["MarqueId"] = new SelectList(_context.Marques, "MarqueId", "Nom");
            ViewData["ModeleId"] = new SelectList(_context.Modeles, "ModeleId", "Nom");
            ViewData["FinitionId"] = new SelectList(_context.Finitions, "FinitionId", "Nom");

            return View();
        }

        // POST: Vehicules/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(Vehicule vehicule, IFormFile? imageFile, bool estVenduChoisi)

        {
            

            if (ModelState.IsValid)
            {
                if (imageFile != null && imageFile.Length > 0)
                {
                    var uploadsFolder = Path.Combine(_env.WebRootPath, "uploads");
                    Directory.CreateDirectory(uploadsFolder);

                    var fileName = $"{Guid.NewGuid()}{Path.GetExtension(imageFile.FileName)}";
                    var filePath = Path.Combine(uploadsFolder, fileName);

                    using var stream = new FileStream(filePath, FileMode.Create);
                    await imageFile.CopyToAsync(stream);

                    vehicule.ImagePath = "/uploads/" + fileName;
                }

                vehicule.EstVendu = estVenduChoisi;
                if (estVenduChoisi)
                {
                    vehicule.DateVente ??= DateTime.Today;
                }
                else
                {
                    vehicule.DateVente = null;
                }

                _context.Add(vehicule);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // IMPORTANT : recharger les dropdown si erreur validation
            ViewData["MarqueId"] = new SelectList(_context.Marques, "MarqueId", "Nom", vehicule.MarqueId);
            ViewData["ModeleId"] = new SelectList(_context.Modeles, "ModeleId", "Nom", vehicule.ModeleId);
            ViewData["FinitionId"] = new SelectList(_context.Finitions, "FinitionId", "Nom", vehicule.FinitionId);
            return View(vehicule);
        }




        // GET: Vehicules/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _context.Vehicules.FindAsync(id);
            if (vehicule == null)
            {
                return NotFound();
            }
            ViewData["MarqueId"] = new SelectList(_context.Marques, "MarqueId", "Nom");
            ViewData["ModeleId"] = new SelectList(_context.Modeles, "ModeleId", "Nom");
            ViewData["FinitionId"] = new SelectList(_context.Finitions, "FinitionId", "Nom");

            return View(vehicule);
        }

        // POST: Vehicules/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, Vehicule vehicule, IFormFile? imageFile, bool estVenduChoisi)

        {
            if (id != vehicule.VehiculeId) return NotFound();

            var vehiculeDb = await _context.Vehicules.FirstOrDefaultAsync(v => v.VehiculeId == id);
            if (vehiculeDb == null) return NotFound();

            if (!ModelState.IsValid)
            {
                ViewData["FinitionId"] = new SelectList(_context.Finitions, "FinitionId", "Nom", vehicule.FinitionId);
                ViewData["MarqueId"] = new SelectList(_context.Marques, "MarqueId", "Nom", vehicule.MarqueId);
                ViewData["ModeleId"] = new SelectList(_context.Modeles, "ModeleId", "Nom", vehicule.ModeleId);
                return View(vehicule);
            }

            // Copier champs
            vehiculeDb.CodeVIN = vehicule.CodeVIN;
            vehiculeDb.Annee = vehicule.Annee;
            vehiculeDb.MarqueId = vehicule.MarqueId;
            vehiculeDb.ModeleId = vehicule.ModeleId;
            vehiculeDb.FinitionId = vehicule.FinitionId;

            vehiculeDb.DateAchat = vehicule.DateAchat;
            vehiculeDb.PrixAchat = vehicule.PrixAchat;
            vehiculeDb.DateVente = vehicule.DateVente;
            vehiculeDb.PrixVente = vehicule.PrixVente;

            vehiculeDb.Description = vehicule.Description;

            vehiculeDb.EstVendu = estVenduChoisi;
            if (estVenduChoisi)
            {
                // Si vendu et aucune date, on met aujourd’hui
                vehiculeDb.DateVente ??= DateTime.Today; 
            }
            else
            {
                // Dispo => pas de date de vente
                vehiculeDb.DateVente = null; 
            }



            // Image : seulement si nouveau fichier
            if (imageFile != null && imageFile.Length > 0)
            {
                var uploadsFolder = Path.Combine(_env.WebRootPath, "uploads");
                Directory.CreateDirectory(uploadsFolder);

                var fileName = $"{Guid.NewGuid()}{Path.GetExtension(imageFile.FileName)}";
                var filePath = Path.Combine(uploadsFolder, fileName);

                using var stream = new FileStream(filePath, FileMode.Create);
                await imageFile.CopyToAsync(stream);

                vehiculeDb.ImagePath = "/uploads/" + fileName;
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }




        // GET: Vehicules/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicule = await _context.Vehicules
                .Include(v => v.Finition)
                .Include(v => v.Marque)
                .Include(v => v.Modele)
                .FirstOrDefaultAsync(m => m.VehiculeId == id);
            if (vehicule == null)
            {
                return NotFound();
            }

            return View(vehicule);
        }

        // POST: Vehicules/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicule = await _context.Vehicules.FindAsync(id);
            if (vehicule != null)
            {
                _context.Vehicules.Remove(vehicule);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

       
    }
}

ExpressVoitures/ExpressVoitures/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpressVoitures</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpressVoitures.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            @if (User.IsInRole("Admin"))
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-danger"
                       href="#"
                       role="button"
                       data-bs-toggle="dropdown">
                        Administration
                    </a>

                    <ul class="dropdown-menu">
                        <li>
                            <a class="dropdown-item" asp-controller="Admin" asp-action="Index">
                                👤 Gestion des utilisateurs
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" asp-controller="Vehicules" asp-action="Index">
                                🚗 Gérer véhicules
                            </a>
                        </li>

                         <li>
                            <a class="dropdown-item" asp-controller="Reparations" asp-action="Index">
                                🔧 Réparations
                            </a>
                        </li>
                       
                    </ul>
                </li>
            }


            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExpressVoitures</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Admin" asp-action="Index">
                                Admin
                            </a>
                        </li>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ExpressVoitures - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>